### ISSUE TITLE
Implement CLI for Turtle* conversion tools

### ISSUE THREAD

**Issue by keski** [RDFstar/RDFstarTools#13]
The conversion from Turtle* to TTL (and vice versa) should be exposed for use from a command shell.

**Comment by hartig** [comment]
I am not sure I understand what the issue is. We have the classes ConverterRDF2RDFStar and ConverterRDFStar2RDF which provide the command line interfaces for the the classes that implement the actual conversion. So, what is missing?

**Comment by keski** [comment]
Okay, my bad, I somehow overlooked these classes. This is exactly what I was referring to. It would perhaps make sense to add an option for tuning some process parameters (e.g., buffer size) but other than that this issue is already covered.

**Comment by hartig** [comment]
Adding tuning-related parameters to the command line tools is a good idea. I have opened a ticket for it, see #14
