### ISSUE TITLE
Command line tools for conversion should not close System.out

### ISSUE THREAD

**Issue by keski** [RDFstar/RDFstarTools#15]
When writing directly to stdout (i.e. when we don't provide an output file) we should prevent `System.out` from being inadvertently closed by the underlying writer. For example,  we could provide a wrapper for `System.out` that is passed to the formatter instead, e.g.:
```java
outStream = new OutputStream() {
    @Override
    public void write(int b) { System.out.write(b); }

    @Override
    public void flush() { System.out.flush(); }

    @Override
    public void close() {}
};
```

**Comment by hartig** [comment]
Good find. Thanks!
