### ISSUE TITLE
ConverterRDFStar2RDF doesn't support quoted + asserted triples

### ISSUE THREAD

**Issue by langston-barrett** [RDFstar/RDFstarTools#29]
The RDF* report has the following syntax in its second example:
```
PREFIX :    <http://www.example.org/>

:employee38
    :familyName "Smith" ;
    :jobTitle "Assistant Designer" {| :accordingTo :employee22 |} .
```
The banana-braces `{|` and `|}` indicate that the contained triple is both asserted and quoted. However, the converter tool doesn't like this syntax:
```
[pool-1-thread-1] ERROR org.apache.jena.riot - [line: 5, col: 66] Too few elements in embedded triple.
[pool-2-thread-1] ERROR org.apache.jena.riot - [line: 5, col: 66] Too few elements in embedded triple.
@prefix :      <http://www.example.org/> .
:employee38 :familyName "Smith" .
```
Since this same example works fine in recent versions of Apache Jena Fuseki, perhaps just upgrading the version of that dependency would help?

**Comment by hartig** [comment]
This tool was written before Jena supported RDF* (now RDF-star). In fact, some of the code of this tool went into Jena. We currently don't have the resources to maintain this tool anymore. 

Moreover, the conversion as implemented by this tool is not in line with the semantics of RDF-star as defined in the RDF-star report; that is, nested triples in RDF-star do not directly map to pure RDF with the RDF reification vocabulary.

**Comment by langston-barrett** [comment]
Thank you for the quick response and helpful information!

> This tool was written before Jena supported RDF* (now RDF-star). In fact, some of the code of this tool went into Jena. We currently don't have the resources to maintain this tool anymore.

Got it! That might be helpful to put somewhere in the README, perhaps along with recommendations for more current alternatives for these tools (if such exist).

> Moreover, the conversion as implemented by this tool is not in line with the semantics of RDF-star as defined in the RDF-star report; that is, nested triples in RDF-star do not directly map to pure RDF with the RDF reification vocabulary.

Gotcha, so it sounds like `ConverterRDFStar2RDF` doesn't implement [6.1 Mapping RDF-star abstract syntax to RDF](https://www.w3.org/2021/12/rdf-star.html#rdf-star-semantics). I don't suppose you happen to know of any currently-maintained, command-line tool that does...?

**Comment by hartig** [comment]
> Got it! That might be helpful to put somewhere in the README, perhaps along with recommendations for more current alternatives for these tools (if such exist).

Done.

> Gotcha, so it sounds like ConverterRDFStar2RDF doesn't implement [6.1 Mapping RDF-star abstract syntax to RDF](https://www.w3.org/2021/12/rdf-star.html#rdf-star-semantics).

Correct.

> I don't suppose you happen to know of any currently-maintained, command-line tool that does...?

No I don't. However, I am also not entirely sure what the value of such a tool would be. I mean, the purpose of this unstar mapping in Sec.6.1 of the spec is for defining the RDF-star semantics. If you are considering to use this mapping for converting RDF-star graphs into pure RDF graphs, make sure to read Sections [6.4.1](https://www.w3.org/2021/12/rdf-star.html#implementing-the-rdf-star-semantics), [6.4.2](https://www.w3.org/2021/12/rdf-star.html#combining-rdf-star-graphs), and in particular [6.4.3](https://www.w3.org/2021/12/rdf-star.html#other-uses-of-the-unstar-mapping).

**Comment by langston-barrett** [comment]
> If you are considering to use this mapping for converting RDF-star graphs into pure RDF graphs, make sure to read Sections [6.4.1](https://www.w3.org/2021/12/rdf-star.html#implementing-the-rdf-star-semantics), [6.4.2](https://www.w3.org/2021/12/rdf-star.html#combining-rdf-star-graphs), and in particular [6.4.3](https://www.w3.org/2021/12/rdf-star.html#other-uses-of-the-unstar-mapping).

Thanks for the tips! Luckily, my use-case doesn't depend on many of the semantic intricacies like referential transparency vs. opacity, since I'm not performing much OWL-style reasoning. I was able to hack something together with the Jena API:

```java
import org.apache.jena.graph.Graph;
import org.apache.jena.graph.Factory;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.impl.NTripleWriter;
import org.apache.jena.riot.Lang;
import org.apache.jena.riot.RDFParser;
import org.apache.jena.riot.system.ErrorHandlerFactory;
import org.apache.jena.system.RDFStar;

class Reify {
    public static void main(String[] _args) {
        Graph in = Factory.createDefaultGraph();
        RDFParser
            .create()
            .checking(true)
            .errorHandler(ErrorHandlerFactory.errorHandlerStrictSilent())
            .source(System.in)
            .lang(Lang.TURTLE)
            .parse(in);
        Graph out = RDFStar.encodeAsRDF(in);
        assert out.isEmpty() == in.isEmpty();
        Model m = ModelFactory.createModelForGraph(out);
        new NTripleWriter().write(m, System.out, null);
    }
}
```
